FROM public.ecr.aws/lambda/python:3.12

COPY aws/requirements-lambda.txt ./
RUN pip install -r requirements-lambda.txt --no-cache-dir

COPY aws/ingest_handler.py ./

CMD ["ingest_handler.lambda_handler"]
